- name: Remove kubernetes repository
  yum_repository:
    name: Kubernetes
    state: absent

- name: Remove docker repository
  yum_repository:
    name: Docker
    state: absent


- name: Remove required packages
  yum: name={{ item }} state=absent
  with_items:
    - "docker-ce-{{ docker_version }}"
    - "kubernetes-cni-{{ cni_version }}"
    - "kubelet-{{ k8s_version }}"

- name: Remove Docker proxy settings
  file: path=/etc/systemd/system/docker.service.d/proxy.conf state=absent

- name: Remove docker dropin directory
  file: path=/etc/systemd/system/docker.service.d state=absent