- name: Ensure directories exist
  file: state=directory path={{ item }}
  with_items:
    - /etc/kubernetes/kubeconfigs
    - /etc/kubernetes/pki
    - /run/systemd/system/docker.service.d
    - /etc/docker

- name: Docker proxy settings
  template: src=templates/docker-proxy.conf.j2 dest=/run/systemd/system/docker.service.d/proxy.conf
  when: nais_http_proxy is defined

# Check if sensu-core exist
- name: Check if sensu core is installed
  command: rpm -q sensu
  ignore_errors: yes
  register: sensu_rpm_check
  tags:
    - skip_ansible_lint
