- hosts: masters:workers
  user: "{{ remote_user }}"
  become: yes
  tasks:
  - name: Copy flannel service file
    template: src=templates/flannel.service.j2 dest=/etc/systemd/system/flannel.service

  - name: copy new docker service file
    copy: src=files/docker.service dest=/etc/systemd/system/docker.service

  - name: daemon reload docker
    systemd:
      daemon_reload=yes
      name=docker

  - name: restart flannel
    systemd:
      name=flannel
      daemon_reload=yes
      state=restarted
