---
# Common initialization play (webproxy, certificates, repositories)
- hosts: all
  user: deployer
  roles:
    - initialization

# Check and copy CA from master play
- hosts: masters
  user: deployer
  roles:
    - check_for_and_copy_master_certificates

# Generate master certificates
- hosts: localhost
  roles:
    - generate_master_certificates

# Copy certificates to master
- hosts: masters
  user: deployer
  become: yes
  tasks:

  - name: Ensure PKI directory exists on master
    file: state=directory path=/etc/kubernetes/pki

  - name: Copy certificates
    copy: src=target/pki/master/ dest=/etc/kubernetes/pki/

# Configure kubernetes Master node
- hosts: masters
  user: deployer
  become: yes
  tasks:
  
  - name: Ensure manifests directory exists on master
    file: state=directory path=/etc/kubernetes/manifests

  - name: Copy kubelet service manifest
    copy: src=files/kubelet.service dest=/etc/systemd/system/kubelet.service

  - name: Ensure kubectl is installed
    environment: "{{ proxy_env}}"
    yum: name=kubectl state=latest
  
  - name: Copy API server pod description
    file: src=files/kubectl-config dest=/root/.kube/config

  - name: Enable kubelet
    systemd:
      daemon_reload=yes
      name=kubelet
      state=started
      enabled=yes

  - name: Copy ETCD pod description
    copy: src=files/etcd.yaml dest=/etc/kubernetes/manifests

  - name: Copy API server pod description
    template: src=templates/kube-apiserver.j2 dest=/etc/kubernetes/manifests/kube-apiserver.yaml
  
  - name: Copy scheduler configuration file
    copy: src=files/scheduler.conf dest=/etc/kubernetes/scheduler.conf

  - name: Copy scheduler server pod description
    template: src=templates/kube-scheduler.j2 dest=/etc/kubernetes/manifests/kube-scheduler.yaml
  
