---
# Check and copy CA from master play
- hosts: master
  user: deployer
  tasks:

  - name: Check master for CA cert
    stat: 
      path: /etc/kubernetes/pki/ca.pem
    register: ca

  - name: Check master for CA cert
    stat: 
      path: /etc/kubernetes/pki/kube-apiserver-server.pem
    register: apiserver

  - fetch: 
      src: /etc/kubernetes/pki/ca.pem
      dest: pki/
      flat: yes
    when: ca.stat.exists 

  - fetch: 
      src: /etc/kubernetes/pki/ca-key.pem
      dest: pki/
      flat: yes
    when: ca.stat.exists 

  - fetch: 
      src: /etc/kubernetes/pki/kube-apiserver-server.pem
      dest: pki/
      flat: yes
    when: apiserver.stat.exists

# Generate CA certificates
- hosts: localhost
  tasks:
  - name: Ensure PKI directory exists
    file: state=directory path=pki/

  - name: Generate ca-csr.json
    template: src=templates/ca-csr.j2 dest=pki/ca-csr.json

  - name: Generate ca-csr.json
    template: src=templates/kube-apiserver-server-csr.j2 dest=pki/kube-apiserver-server-csr.json
  
  - name: Copy ca-config.json
    copy: src=files/ca-config.json dest=pki/ca-config.json

  - name: Initializing the CA
    shell: bin/cfssl gencert -initca pki/ca-csr.json | bin/cfssljson -bare pki/ca
    args:
      creates: pki/ca.pem

  - name: Creating kube apiserver certificate
    shell: bin/cfssl gencert -ca=pki/ca.pem -ca-key=pki/ca-key.pem -config=pki/ca-config.json -profile=server pki/kube-apiserver-server-csr.json | bin/cfssljson -bare pki/kube-apiserver-server
    args:
      creates: pki/kube-apiserver-server.pem

# Common initialization play

- hosts: all
  user: deployer
  tasks:

  - name: Add kubernetes repository
    become: yes
    yum_repository:
      name: Kubernetes
      description: Kubernetes
      file: kubernetes
      baseurl: http://yum.kubernetes.io/repos/kubernetes-el7-x86_64
      enabled: true
      gpgcakey: https://packages.cloud.google.com/yum/doc/yum-key.gpg
      gpgkey: https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg  
      gpgcheck: true
      state: present

  - name: Ensure certs directory exists
    become: yes
    file: state=directory path=/etc/pki/ca-trust/source/anchors/

  - name: Install proxy cert
    become: yes
    copy: src=files/webproxy.crt dest=/etc/pki/ca-trust/source/anchors/webproxy.crt
    notify: update_cert_index
  
  - meta: flush_handlers

  handlers:
  - name: update_cert_index
    become: yes
    shell: /usr/bin/update-ca-trust

  - name: load_sysctl_config
    become: yes
    shell: /sbin/sysctl -p /etc/sysctl.d/k8s.conf

#- hosts: {{environment}}_masters
#  user: deployer
#  
#  tasks: 
#  - name: test
#    shell: echo hei 
#
