---
# Common initialization play
- hosts: all
  user: deployer
  roles:
    - initialization

# Check and copy CA from master play
- hosts: masters
  user: deployer
  roles:
    - check_for_and_copy_master_certificates

# Generate master certificates
- hosts: localhost
  roles:
    - generate_master_certificates

# Copy certificates to master
- hosts: masters
  user: deployer
  become: yes
  tasks:

  - name: Ensure PKI directory exists on master
    file: state=directory path=/etc/kubernetes/pki

  - name: Copy certificates
    copy: src=target/pki/master/ dest=/etc/kubernetes/pki/
