---

# Common initialization play

- hosts: all
  user: deployer
  tasks:

  - name: test
    environment: "{{proxy_env}}"
    shell: echo {{proxy_env['banankake']}}

  - name: Add kubernetes repository
    become: yes
    yum_repository:
      name: Kubernetes
      description: Kubernetes
      file: kubernetes
      baseurl: http://yum.kubernetes.io/repos/kubernetes-el7-x86_64
      enabled: true
      gpgcakey: https://packages.cloud.google.com/yum/doc/yum-key.gpg
      gpgkey: https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg  
      gpgcheck: true
      state: present

  - name: Ensure certs directory exists
    become: yes
    file: state=directory path=/etc/pki/ca-trust/source/anchors/

  - name: Install proxy cert
    become: yes
    copy: src=files/webproxy.crt dest=/etc/pki/ca-trust/source/anchors/webproxy3.crt
    notify: update_cert_index
  
  - meta: flush_handlers

  handlers:
  - name: update_cert_index
    become: yes
    shell: /usr/bin/update-ca-trust

  - name: load_sysctl_config
    become: yes
    shell: /sbin/sysctl -p /etc/sysctl.d/k8s.conf

#- hosts: {{environment}}_masters
#  user: deployer
#  
#  tasks: 
#  - name: test
#    shell: echo hei 
