---
# Remove things created by common initialization play (webproxy, certificates, repositories)
- hosts: all
  user: deployer
  become: yes
  roles:
    - revert_common

- hosts: masters
  user: deployer
  roles:
    - remove_existing_certificates

- hosts: localhost
  roles:
    - remove_certificates