---
# Common initialization play (webproxy, certificates, repositories)
- hosts: all
  user: deployer
  become: yes
  roles:
    - common

- hosts: masters
  user: deployer
  roles:
    - fetch_existing_certificates

- hosts: localhost
  roles:
    - create_certificates

# Configure kubernetes Master node
- hosts: masters
  user: deployer
  become: yes
  roles: 
    - etcd

  tasks:

  - name: Copy certificates
    copy: src=target/pki/{{ item }} dest=/etc/kubernetes/pki/
    with_items:
      - admin.pem
      - admin-key.pem
      - ca.pem
      - ca-key.pem
      - kube-apiserver-server-key.pem
      - kube-apiserver-server.pem
      - sa.key
      - sa.pub


  - name: Check if flannel config exists (OK if this fails)
    shell: /usr/bin/etcdctl ls /nais/network/config
    environment: 
      - ETCDCTL_API: 2
    register: flannelconfig
    ignore_errors: yes

  - name: Set flannel configuration in etcd
    shell: '/usr/bin/etcdctl mkdir /nais/network && \
           /usr/bin/etcdctl mk /nais/network/config  "{ \"Network\": \"{{ pod_network_cidr }}\", \"SubnetLen\": 23, \"Backend\": { \"Type\": \"vxlan\" }}"'
    environment: 
      - ETCDCTL_API: 2
    when: flannelconfig.rc != 0


- hosts: all
  user: deployer
  become: yes
  tasks:

  - name: Download flannel binaries # using curl as get_url gave protocol error (most likely caused by internal webproxy)
    environment: "{{ proxy_env }}"
    shell: curl -L --insecure https://github.com/coreos/flannel/releases/download/v{{flannel_version}}/flannel-v{{flannel_version}}-linux-amd64.tar.gz | \
           tar xzf - -C /tmp flanneld mk-docker-opts.sh && \
           mv /tmp/flanneld /usr/bin/flanneld-{{flannel_version}} && \
           mv /tmp/mk-docker-opts.sh /usr/libexec
    args:
      creates: /usr/bin/flanneld-{{flannel_version}}

  - name: Symlink flannel
    file: src=/usr/bin/flanneld-{{flannel_version}} dest=/usr/bin/flanneld state=link

  - name: Copy flannel service file
    template: src=templates/flannel.service.j2 dest=/etc/systemd/system/flannel.service

  - name: Enable flannel
    systemd:
      daemon_reload=yes
      name=flannel
      state=restarted
      enabled=yes

  - name: Make flannel configuration for docker
    shell: mkdir -p /var/lib/docker && rm -f /var/lib/docker/docker_opts.env && /usr/libexec/mk-docker-opts.sh -k DOCKER_OPTS -f /run/flannel/subnet.env -d /var/lib/docker/docker_opts.env

  - name: Copy docker service file
    copy: src=files/docker.service dest=/etc/systemd/system/docker.service
    notify:
      - restart_docker

  - name: Start and enable docker
    systemd:
      daemon_reload=yes
      name=docker
      state=started
      enabled=yes

  - name: Enable IP forwarding
    iptables:
      chain: FORWARD
      policy: ACCEPT

  - name: Download kube-proxy binaries # using curl as get_url gave protocol error (most likely caused by internal webproxy)
    environment: "{{ proxy_env }}"
    shell: curl --insecure https://storage.googleapis.com/kubernetes-release/release/v{{ k8s_version }}/bin/linux/amd64/kube-proxy > /usr/bin/kube-proxy
    args:
      creates: /usr/bin/kube-proxy

  - name: Make kube-proxy executable
    file: path=/usr/bin/kube-proxy mode=0755

  - name: Copy kube-proxy service file
    template: src=templates/kube-proxy.service.j2 dest=/etc/systemd/system/kube-proxy.service
    notify:
      - restart_kubeproxy

  - name: Copy kube-proxy kubeconfig
    template: src=templates/kubeconfigs/kube-proxy.conf.j2 dest=/etc/kubernetes/kubeconfigs/kube-proxy.conf
    notify: 
      - restart_kubeproxy

  - name: Enable kube-proxy
    systemd:
      daemon_reload=yes
      name=kube-proxy
      state=started
      enabled=yes

  - name: Clean up /etc/hosts after puppet
    shell: /bin/sed -i "s/$(/sbin/ifconfig docker0 | grep inet | awk '{print $2}')/$(/sbin/ifconfig $(ls /sys/class/net/ | grep en) | grep inet | awk '{print $2}')/g" /etc/hosts

  handlers:
    - name: restart_docker
      systemd:
        daemon_reload=yes
        name=docker
        state=restarted

    - name: restart_kubeproxy
      systemd:
        daemon_reload=yes
        name=kube-proxy
        state=restarted

# Start control plane
- hosts: masters
  user: deployer
  become: yes
  tasks:
  
  - name: Copy kubelet service manifest
    copy: src=files/master-kubelet.service dest=/etc/systemd/system/kubelet.service
    notify: 
      - restart_kubelet

  - name: Ensure kubectl is installed
    environment: "{{ proxy_env }}"
    yum: name=kubectl state=latest
  
  - name: Enable kubelet
    systemd:
      daemon_reload=yes
      name=kubelet
      state=started
      enabled=yes

  - name: Ensure kubectl config directory exists on master
    file: state=directory path=/root/.kube

  - name: Copy API server pod description
    copy: src=files/kubectl-config dest=/root/.kube/config

  - name: Ensure manifests directory exists on master
    file: state=directory path=/etc/kubernetes/manifests

  - name: Copy manifests and kubeconfigs
    template: src=templates/{{ item }}.j2 dest=/etc/kubernetes/{{ item }}
    with_items:
      - manifests/kube-apiserver.yaml
      - manifests/kube-scheduler.yaml
      - manifests/kube-controller-manager.yaml
      - kubeconfigs/kube-scheduler.conf
      - kubeconfigs/kube-controller-manager.conf
    notify: 
      - restart_docker
  
  handlers:
    - name: restart_docker
      systemd:
        name=docker
        daemon_reload=yes
        state=restarted

    - name: restart_kubelet
      systemd:
        name=kubelet
        daemon_reload=yes
        state=restarted

# Configure workers
- hosts: workers
  user: deployer
  become: yes
  tasks:
  
  - name: Copy certificates
    copy: src=target/pki/{{ item }} dest=/etc/kubernetes/pki/ # to ensure idempotency
    with_items:
      - admin.pem
      - admin-key.pem
      - ca.pem
    notify:
      - restart_kubelet
      - restart_kubeproxy

  - name: Copy kubelet service manifest
    template: src=templates/worker-kubelet.service.j2 dest=/etc/systemd/system/kubelet.service
    notify: 
      - restart_kubelet

  - name: Copy kubelet kubeconfig
    template: src=templates/kubeconfigs/kubelet.conf.j2 dest=/etc/kubernetes/kubeconfigs/kubelet.conf
    notify: 
      - restart_kubelet

  - name: Enable kubelet
    systemd:
      daemon_reload=yes
      name=kubelet
      state=started
      enabled=yes

  handlers:
    - name: restart_kubeproxy
      systemd:
        daemon_reload=yes
        name=kube-proxy
        state=restarted

    - name: restart_kubelet
      systemd:
        daemon_reload=yes
        name=kubelet
        state=restarted


# Install kubernetes addons
- hosts: masters
  user: deployer
  become: yes

  tasks:
  - name: Ensure addons directory exists
    file: state=directory path=/etc/kubernetes/addons

  - name: Copy kubernetes-addons manifest templates
    template: src=templates/addons/{{ item }}.j2 dest=/etc/kubernetes/addons/{{ item }}
    with_items:
      - kubernetes-dashboard.yaml
      - core-dns.yaml
      - traefik.yaml
      - heapster.yaml

  - name: Create addons
    shell: /usr/bin/kubectl create -f /etc/kubernetes/addons/{{ item }}
    with_items:
      - kubernetes-dashboard.yaml
      - core-dns.yaml
      - traefik.yaml
      - heapster.yaml
    ignore_errors: yes
  
  - name: Download helm binaries
    environment: "{{ proxy_env }}"
    shell: curl -L --insecure https://storage.googleapis.com/kubernetes-helm/helm-v{{ helm_version }}-linux-amd64.tar.gz | \
           tar xzf - -C /tmp linux-amd64/helm && \
           mv /tmp/linux-amd64/helm /usr/bin/helm-{{ helm_version }}
    args:
      creates: /usr/bin/helm-{{ helm_version }}
   
  - name: Symlink helm
    file: src=/usr/bin/helm-{{ helm_version }} dest=/usr/bin/helm state=link

  - name: Initialize helm
    environment: "{{ proxy_env }}"
    shell: /usr/bin/helm init
