---
# proxy role
- hosts: all
  user: "{{ remote_user }}"
  become: yes
  tasks:
  - name: Remove certificate
    file: path=/etc/pki/ca-trust/source/anchors/webproxy.crt state=absent

  - name: update_cert_index
    shell: /usr/bin/update-ca-trust

- hosts: masters:workers
  user: "{{ remote_user }}"
  become: yes
  tasks:
    - name: Remove kubernetes repository
      yum_repository:
        name: Kubernetes
        state: absent

    - name: Remove docker repository
      yum_repository:
        name: Docker
        state: absent

    - name: Stop services
      shell: timeout 15 /bin/systemctl stop {{ item }}
      with_items:
        - kubelet
        - docker
      ignore_errors: yes

    - name: Disable services
      shell: timeout 15 /bin/systemctl disable {{ item }}
      with_items:
        - kubelet
        - docker
      ignore_errors: yes

    - name: Remove required packages
      yum: name={{ item }} state=absent
      with_items:
        - "docker-ce"

    - name: Remove files
      file: path={{ item }} state=absent
      with_items:
        - /etc/systemd/system/docker.service.d
        - /etc/systemd/system/kubelet.service
        - /etc/kubernetes
        - /etc/docker

    - name: Unmount docker resources
      shell: /bin/umount {{ item }}
      with_items:
        - /run/docker/netns/*
        - /var/lib/docker/overlay
      ignore_errors: yes

    - name: Get mounted kubelet resources
      shell: " mount |grep /var/lib/kubelet/pods | cut -d ' ' -f 3 "
      register: kubelet_resources
      ignore_errors: yes

    - name:  umount kubelet resources
      shell: " umount {{ item }} "
      when: kubelet_resources.stdout_lines|length > 0
      with_items: " {{kubelet_resources.stdout_lines }} "

- hosts: masters
  user: "{{ remote_user }}"
  become: yes
  tasks:
    - name: Remove files
      file: path={{ item }} state=absent
      with_items:
        - /root/.helm/repository/repositories.yaml
        - /usr/bin/helm-{{helm_version}}
        - /usr/bin/helm
        - /etc/sensu/conf.d/nais_master_metrics.json

- hosts: etcd
  user: "{{ remote_user }}"
  become: yes
  tasks:
    - name: Disable etcd
      systemd: name=etcd enabled=no state=stopped
      ignore_errors: yes
    - name: Remove files
      file: path={{ item }} state=absent
      with_items:
        - /usr/bin/etcd-{{etcd_version}}
        - /usr/bin/etcd
        - /usr/bin/etcdctl-{{etcd_version}}
        - /usr/bin/etcdctl
        - /var/lib/etcd
        - /etc/systemd/system/etcd.service

- hosts: workers
  user: "{{ remote_user }}"
  become: yes
  tasks:
    - name: Remove files
      file: path={{ item }} state=absent
      with_items:
        - /etc/sensu/conf.d/nais_worker_metrics.json

- hosts: localhost
  tasks:
    - name: Remove target folder
      file: path=target state=absent

- hosts: masters:workers
  user: "{{ remote_user }}"
  become: yes
  tasks:
  - name: Stop services
    systemd:
      name={{ item }}
      state=stopped
      enabled=no
    with_items:
      - kube-proxy
      - flannel
    ignore_errors: yes

  - name: Remove files
    file: path={{ item }} state=absent
    with_items:
      - /etc/systemd/system/kubelet.service
      - /usr/bin/kube-proxy*
      - /usr/bin/kubelet*
      - /usr/bin/kubectl*
      - /etc/systemd/system/kube-proxy.service
      - /usr/libexec/mk-docker-opts.sh
      - /usr/bin/flanneld
      - /etc/systemd/system/flannel.service
      - /etc/systemd/system/docker.service
      - /usr/bin/flanneld-{{flannel_version}}
      - /run/docker_opts.env
      - /run/flannel/subnet.env
      - /var/lib/docker
      - /var/lib/dockershim
      - /var/lib/kubelet
      - /var/lib/kubernetes
      - /var/run/docker
      - /var/run/flannel
      - /var/run/kubernetes
      - /run/docker
      - /run/flannel
      - /run/kubernetes

  - name: Remove docker interface
    shell: ip link delete docker0
    ignore_errors: yes

  - name: Remove flannel interface
    shell: ip link delete flannel.1
    ignore_errors: yes

  - name: Remove nais sensu check directory
    file: path=/etc/sensu/plugins/metrics/nais state=absent
