---
# proxy role
- hosts: all
  user: "{{ remote_user }}"
  become: yes
  tasks:
  - name: Remove certificate
    file: path=/etc/ssl/certs/webproxy.pem state=absent

  - name: update_cert_index
    command: /sbin/update-ca-certificates
    changed_when: false

- hosts: masters:workers
  user: "{{ remote_user }}"
  become: yes
  tasks:
    - name: Stop services
      command: timeout 15 /bin/systemctl stop {{ item }}
      with_items:
        - kubelet
        - docker
      ignore_errors: yes
      changed_when: false

    - name: Disable services
      command: timeout 15 /bin/systemctl disable {{ item }}
      with_items:
        - kubelet
        - docker
      ignore_errors: yes
      changed_when: false

    - name: Remove files
      file: path={{ item }} state=absent
      with_items:
        - /etc/systemd/system/docker.service.d
        - /etc/systemd/system/kubelet.service
        - /etc/kubernetes

    - name: Get mounted kubelet resources
      shell: "mount | grep /var/lib/kubelet/pods | cut -d ' ' -f 3"
      register: kubelet_resources
      ignore_errors: yes
      changed_when: false
      tags:
        - skip_ansible_lint

    - name:  umount kubelet resources
      command: "umount {{ item }}"
      when: kubelet_resources.stdout_lines|length > 0
      with_items: "{{ kubelet_resources.stdout_lines }}"

- hosts: masters
  user: "{{ remote_user }}"
  become: yes
  tasks:
    - name: Remove files
      file: path={{ item }} state=absent
      with_items:
        - /root/.helm/repository/repositories.yaml
        - "{{ install_dir }}/bin/helm-{{helm_version}}"
        - "{{ install_dir }}/bin/helm"
        - /etc/sensu/conf.d/nais_master_metrics.json

- hosts: etcd
  user: "{{ remote_user }}"
  become: yes
  tasks:
    - name: Disable etcd
      systemd: name=etcd enabled=no state=stopped
      ignore_errors: yes
    - name: Remove files
      file: path={{ item }} state=absent
      with_items:
        - "{{ install_dir }}/bin/etcd-{{etcd_version}}"
        - "{{ install_dir }}/bin/etcd"
        - "{{ install_dir }}/bin/etcdctl-{{etcd_version}}"
        - "{{ install_dir }}/bin/etcdctl"
        - /var/lib/etcd
        - /etc/systemd/system/etcd.service

- hosts: workers
  user: "{{ remote_user }}"
  become: yes
  tasks:
    - name: Remove files
      file: path={{ item }} state=absent
      with_items:
        - /etc/sensu/conf.d/nais_worker_metrics.json

- hosts: localhost
  tasks:
    - name: Remove target folder
      file: path=target state=absent

- hosts: masters:workers
  user: "{{ remote_user }}"
  become: yes
  tasks:
  - name: Stop services
    systemd:
      name={{ item }}
      state=stopped
      enabled=no
    with_items:
      - kube-proxy
      - flannel
    ignore_errors: yes

  - name: Remove files
    file: path={{ item }} state=absent
    with_items:
      - /etc/systemd/system/kubelet.service
      - "{{ install_dir }}/bin/kube-proxy*"
      - "{{ install_dir }}/bin/kubelet*"
      - "{{ install_dir }}/bin/kubectl*"
      - /etc/systemd/system/kube-proxy.service
      - "{{ install_dir }}/mk-docker-opts.sh"
      - "{{ install_dir }}/bin/flanneld"
      - /etc/systemd/system/flannel.service
      - /etc/systemd/system/docker.service
      - "{{ install_dir }}/bin/flanneld-{{flannel_version}}"
      - /run/docker_opts.env
      - /run/flannel/subnet.env
      - /var/lib/docker
      - /var/lib/dockershim
      - /var/lib/kubelet
      - /var/lib/kubernetes
      - /var/run/flannel
      - /var/run/kubernetes
      - /run/flannel
      - /run/kubernetes
      - /root/.docker

  - name: Remove flannel interface
    command: ip link delete flannel.1
    ignore_errors: yes
    changed_when: false

  - name: Remove nais sensu check directory
    file: path=/etc/sensu/plugins/metrics/nais state=absent

- hosts: coreos
  user: "{{ remote_user }}"
  become: yes
  tasks:
  - name: Remove python bootstrap file
    file: path={{ ansible_pypy_bootstrap_file }} state=absent

  - name: Remove python interpreter
    raw: rm -rf {{ ansible_python_interpreter }} {{ ansible_pypy_home }} 
