---
# Remove things created by common initialization play (webproxy, certificates, repositories)
- hosts: all
  user: deployer
  become: yes
  tasks:
    - name: Remove kubernetes repository
      yum_repository:
        name: Kubernetes
        state: absent
    
    - name: Remove docker repository
      yum_repository:
        name: Docker
        state: absent
    
   
    - name: Stop services
      systemd:
        name={{ item }}
        state=stopped
        enabled=no
      with_items:
        - kubelet
        - docker
      ignore_errors: yes

    - name: Remove required packages
      yum: name={{ item }} state=absent
      with_items:
        - "docker-ce"
        - "kubernetes-cni"
        - "kubelet"
    
    - name: Remove files
      file: path={{ item }} state=absent
      with_items:
        - /etc/systemd/system/docker.service.d
        - /etc/systemd/system/kubelet.service
        - /etc/kubernetes
        - /etc/docker

- hosts: masters
  user: deployer
  become: yes
  tasks:
    - name: Remove files
      file: path={{ item }} state=absent 
      with_items:
        - /usr/bin/etcd-{{etcd_version}}
        - /usr/bin/etcd
        - /usr/bin/etcdctl-{{etcd_version}}
        - /usr/bin/etcdctl
        - /var/lib/etcd
        - /etc/systemd/system/etcd.service

    - name: Disable etcd 
      systemd: name=etcd enabled=no state=stopped 
      ignore_errors: yes

- hosts: localhost
  tasks:
    - name: Remove target folder
      file: path=target state=absent

- hosts: workers
  user: deployer
  become: yes
  tasks:
  - name: Stop services
    systemd:
      name={{ item }}
      state=stopped
      enabled=no
    with_items:
      - kube-proxy
      - flannel
    ignore_errors: yes

  - name: Remove files
    file: path={{ item }} state=absent
    with_items:
      - /etc/systemd/system/kubelet.service
      - /usr/bin/kube-proxy
      - /etc/systemd/system/kube-proxy.service
      - /usr/libexec/mk-docker-opts.sh
      - /usr/bin/flanneld
      - /etc/systemd/system/flannel.service
      - /etc/systemd/system/docker.service
      - /usr/bin/flanneld-{{flannel_version}}
      - /run/docker_opts.env
      - /run/flannel/subnet.env
      - /var/run/docker
      - /var/run/flannel
      - /var/run/kubernetes
      - /run/docker
      - /run/flannel
      - /run/kubernetes

  - name: Remove docker interface
    shell: ip link delete docker0 
    ignore_errors: yes
 
  - name: Remove flannel interface
    shell: ip link delete flannel.1 
    ignore_errors: yes
