- name: Ensure directories exist
  file:
    state: directory
    path: "{{ cert_dir }}"

- name: Install proxy cert
  copy:
    src: "{{ role_path }}/files/webproxy.crt"
    dest: "{{ cert_dir }}/webproxy{{ cert_postfix }}"

- name: update_cert_index
  command: "{{ cert_bin }}"
  changed_when: false
