- name: Ensure directories exist
  file: state=directory path=/etc/pki/ca-trust/source/anchors

- name: Install proxy cert
  copy: src=files/webproxy.crt dest=/etc/pki/ca-trust/source/anchors/webproxy.crt

- name: update_cert_index
  command: /usr/bin/update-ca-trust
