- name: Ensure directories exist
  file: state=directory path=/etc/ssl/certs

- name: Install proxy cert
  copy: src=files/webproxy.crt dest=/etc/ssl/certs/webproxy.pem

- name: update_cert_index
  command: /sbin/update-ca-certificates
  changed_when: false
