- name: Ensure PKI directory exists
  file: state=directory path=target/pki/

- name: Ensure master directory exists
  file: state=directory path=target/pki

- name: Generate istio-ingress-csr.json
  template: src=templates/istio-ingress-csr.j2 dest=target/pki/istio-ingress-csr.json

- name: Copy istio-sidecar-injector-csr.json
  copy: src=files/istio-sidecar-injector-csr.json dest=target/istio-sidecar-injector-csr.json

- name: Creating istio-ingress certificate
  shell: bin/cfssl gencert -ca=target/pki/ca.pem -ca-key=target/pki/ca-key.pem -config=target/pki/ca-config.json -profile=server files/istio-ingress-csr.json | bin/cfssljson -bare target/pki/istio-ingress
  args:
    creates: target/pki/istio-ingress.pem

- name: Creating istio-sidecar-injector certificate
  shell: bin/cfssl gencert -ca=target/pki/ca.pem -ca-key=target/pki/ca-key.pem -config=target/pki/ca-config.json -profile=server files/istio-sidecar-injector-csr.json | bin/cfssljson -bare target/pki/istio-sidecar-injector
  args:
    creates: target/pki/istio-sidecar-injector.pem

- name: Adding istio-sidecar-injector certificate secret
  shell:  k create secret generic sidecar-injector-certs --from-file=key.pem=istio-sidecar-injector-key.pem --from-file=cert.pem=istio-sidecar-injector.pem --dry-run -o yaml | kubectl -n istio-system apply -f -

- name: Reading ca-certificate from file
  shell: :

- name: Adding CA bundle to istio-sidecar-injector
  shell: 
