- name: Ensure directories exist
  file: state=directory path={{ item }}
  with_items:
    - /etc/pki/ca-trust/source/anchors
    - /etc/kubernetes/kubeconfigs
    - /etc/kubernetes/pki
    - /etc/systemd/system/docker.service.d 

- name: Install proxy cert
  copy: src=files/webproxy.crt dest=/etc/pki/ca-trust/source/anchors/webproxy.crt
  notify: update_cert_index

- name: Update certificate CA truststore
  meta: flush_handlers

- name: Add kubernetes repository
  yum_repository:
    name: Kubernetes
    description: Kubernetes
    file: kubernetes
    baseurl: http://yum.kubernetes.io/repos/kubernetes-el7-x86_64
    enabled: true
    gpgcakey: https://packages.cloud.google.com/yum/doc/yum-key.gpg
    gpgkey: https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    gpgcheck: true
    state: present

- name: Add docker repository
  yum_repository:
    name: Docker
    description: Docker
    file: docker
    baseurl: https://download.docker.com/linux/centos/7/x86_64/stable
    enabled: true
    gpgkey: https://download.docker.com/linux/centos/gpg
    gpgcheck: true
    state: present

# install docker-selinux package separately to avoid obsoletion errors from newer docker releases
- name: Remove container-selinux
  yum:
    name: container-selinux
    state: absent

- name: Install docker selinux package
  environment: "{{ proxy_env }}"
  shell: "yum -y --setopt=obsoletes=0 install docker-ce-selinux-{{ docker_version }}"

- name: Install required packages
  environment: "{{ proxy_env }}"
  yum: name={{ item }} state=present
  with_items:
    - "docker-ce-{{ docker_version }}"
    - "socat"

- name: Docker proxy settings
  template: src=templates/docker-proxy.conf.j2 dest=/etc/systemd/system/docker.service.d/proxy.conf

- name: Disable puppet agent
  shell: /bin/puppet agent --disable
  ignore_errors: yes

- name: Disable puppet agent (preprod)
  shell: /opt/puppet/bin/puppet agent --disable
  ignore_errors: yes
